version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: tracker_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    env_file:
      - .env
    networks:
      - tracker_net

  nginx:
    image: nginx:latest
    container_name: tracker_nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./src:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tracker_net

networks:
  tracker_net:
    driver: bridge
